# Generated by Django 5.0.6 on 2024-07-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalidadAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.FloatField()),
                ('turbiedad', models.FloatField()),
                ('cloro', models.FloatField()),
                ('nitratos', models.FloatField()),
                ('cloruros', models.FloatField()),
                ('fluor', models.FloatField()),
                ('sodios', models.FloatField()),
                ('conductividad', models.FloatField()),
                ('ica', models.FloatField()),
                ('calificacion', models.CharField(max_length=255)),
            ],
        ),
    ]
